# MNIST

아래의 code는 google colab 에서 시험된 결과이다.
Anaconda 에서 제공되는 jupyter notebook에서는 작동이 안될수 있다.
추천하는 방법은 notebook이 아니라 python 파일 자체를 실행하라는 것이다. TPU 예제만 빼고는 anaconda prompt 에서 *.py 파일을 실행하는 방법을 추천한다.
compare 도구로서는 "BCcompare"를 추천한다. working day로 30일간 무료로 사용이 가능하다.
무료 사용후 재 설치 하면 다시 30 working day동안 사용이 가능하다.

```
from tensorflow.keras.utils import to_categorical
```
는 Y_train/Y_test 의 형식을 one-hot의 형태로 변경하기 위해서 추가 되어진다.

In [4]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical



아래의 코드를 보면
```
Y_train = to_categorical(Y_train, 10)
Y_test = to_categorical(Y_test, 10)   
```
가 추가 되어져 있다.

이는 categorical_crossentropy를 loss 함수로 사용하기 위해서 one-hot으로 변경 해주는 부분이다.

Y_train을 10개를 출력해 보자.

In [5]:
mnist = tf.keras.datasets.mnist

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

print(Y_train[0:10])

Y_train = to_categorical(Y_train, 10)
Y_test = to_categorical(Y_test, 10)    

print(Y_train[0:10].astype(int))

[5 0 4 1 9 2 1 3 1 4]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


출력된 결과는 0~9까지의 숫자로 표현될때와 one-hot으로 표현되어질때를 비교하여 출력한것이다.

```
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
```

"01_tf2_mnist_test_beginner_sparse.py"와 비교하면 loss 함수가 변경된것을 볼수 있다.

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=5, verbose=1)

model.evaluate(X_test,  Y_test, verbose=2)              

"""
verbose default is 1

verbose=0 (silent)

verbose=1 (progress bar)

Train on 186219 samples, validate on 20691 samples
Epoch 1/2
186219/186219 [==============================] - 85s 455us/step - loss: 0.5815 - acc: 
0.7728 - val_loss: 0.4917 - val_acc: 0.8029
Train on 186219 samples, validate on 20691 samples
Epoch 2/2
186219/186219 [==============================] - 84s 451us/step - loss: 0.4921 - acc: 
0.8071 - val_loss: 0.4617 - val_acc: 0.8168


verbose=2 (one line per epoch)

Train on 186219 samples, validate on 20691 samples
Epoch 1/1
 - 88s - loss: 0.5746 - acc: 0.7753 - val_loss: 0.4816 - val_acc: 0.8075
Train on 186219 samples, validate on 20691 samples
Epoch 1/1
 - 88s - loss: 0.4880 - acc: 0.8076 - val_loss: 0.5199 - val_acc: 0.8046
 
 """

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2935 - accuracy: 0.9145
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1418 - accuracy: 0.9585
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1049 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0870 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0746 - accuracy: 0.9763
313/313 - 0s - loss: 0.0708 - accuracy: 0.9781


'\nverbose default is 1\n\nverbose=0 (silent)\n\nverbose=1 (progress bar)\n\nTrain on 186219 samples, validate on 20691 samples\nEpoch 1/2\n186219/186219 [==============================] - 85s 455us/step - loss: 0.5815 - acc: \n0.7728 - val_loss: 0.4917 - val_acc: 0.8029\nTrain on 186219 samples, validate on 20691 samples\nEpoch 2/2\n186219/186219 [==============================] - 84s 451us/step - loss: 0.4921 - acc: \n0.8071 - val_loss: 0.4617 - val_acc: 0.8168\n\n\nverbose=2 (one line per epoch)\n\nTrain on 186219 samples, validate on 20691 samples\nEpoch 1/1\n - 88s - loss: 0.5746 - acc: 0.7753 - val_loss: 0.4816 - val_acc: 0.8075\nTrain on 186219 samples, validate on 20691 samples\nEpoch 1/1\n - 88s - loss: 0.4880 - acc: 0.8076 - val_loss: 0.5199 - val_acc: 0.8046\n \n '